config/routes.rb
CucumberTest::Application.routes.draw do

  resources :blog_posts

  devise_for :users, :controllers => { :registrations => 'users/registrations'}

  root to: 'blog_posts#index'
  
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :birthdate, :phone_number, :mobile_number
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_posts }
    end
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(params[:blog_post])

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render json: @blog_post, status: :created, location: @blog_post }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      if @blog_post.update_attributes(params[:blog_post])
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    if user_signed_in?
      if current_user.sign_in_count == 1
        redirect_to edit_user_registration_path
      end
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(params[:user])
    else
      params[:user].delete(:current_password)
      @user.update_without_password(params[:user])
    end

    if successfully_updated
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  private

    def needs_password?(user, params)
      user.email != params[:user][:email] ||
        params[:user][:password].present?
    end

  protected

    def after_update_path_for(resource)
      root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.haml
= form_for @blog_post do |f|
  - if @blog_post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog_post.errors.count, "error")} prohibited this blog_post from being saved:"
      %ul
        - @blog_post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/blog_posts/edit.html.haml
%h1 Editing blog_post

= render 'form'

= link_to 'Show', @blog_post
\|
= link_to 'Back', blog_posts_path

app/views/blog_posts/index.html.haml
%h1 Listing blog_posts

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th

  - @blog_posts.each do |blog_post|
    %tr
      %td= blog_post.title
      %td= blog_post.content
      %td= link_to 'Show', blog_post
      %td= link_to 'Edit', edit_blog_post_path(blog_post)
      %td= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Blog post', new_blog_post_path

app/views/blog_posts/new.html.haml
%h1 New blog_post

= render 'form'

= link_to 'Back', blog_posts_path

app/views/blog_posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @blog_post.title
%p
  %b Content:
  = @blog_post.content

= link_to 'Edit', edit_blog_post_path(@blog_post)
\|
= link_to 'Back', blog_posts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
  %title CucumberTest
  = csrf_meta_tags
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"

  %body
    - if current_user.present?
      %div 
        Olá,
        %strong= current_user.username
        = link_to 'My Account', edit_user_registration_path
        |
        = link_to "Logout", "/users/sign_out", method: :delete
    - else
      %div
        = link_to 'Sign up', new_user_registration_path
        |
        = link_to 'Login', user_session_path
    - if session[:flash] && session[:flash].notice
      .alert.alert-success
        .strong= session[:flash].notice
    - if session[:flash] && session[:flash].alert
      .alert
        .strong= session[:flash].alert
    = yield